### ISSUE TITLE
missing user argument at /usr/local/share/perl/5.18.2/Minilla/Release/UploadToCPAN.pm line 52.

### ISSUE THREAD

**Issue by no-glue** [tokuhirom/Minilla#156]
The message appears when typed minil release.

**Comment by syohex** [comment]
Is there `~/.pause` file or did you specify `pause_config` in TOML configuration file like following snippet ?

```toml
[release]
pause_config = "/path/to/some/.pause"
```
