### ISSUE TITLE
Question. 

### ISSUE THREAD

**Issue by ivanych** [tokuhirom/Minilla#239]
In my project, I use Perl :: Tidy. The perltidy utility takes the settings from the .perltidy file.

I also have a test based on Test :: Perltidy. The test also takes the settings from the .perltidy file.

Problem:

If you run the minil test, the .perltidy file is not copied to the temporary directory,
in which tests are run. As a result, the test can not read the settings from the .perltidy file and is not executed correctly.

Question:

How to make the test read settings from .perltidy?

**Comment by skaji** [comment]
Thanks for creating this issue.

You can use FileGatherer.include_dotfiles in minil.toml:
```toml
[FileGatherer]
include_dotfiles = true
```

**Comment by skaji** [comment]
You can also use exclude_match
```toml
[FileGatherer]
include_dotfiles= true
exclude_match = ['^\.(?!perltidy)']
```  

BTW, I were you, I would set nothing for FileGatherer in minil.toml, and just execute `prove -l t` for test.
